### PR TITLE
Add -P option to prepend relative image paths with a prefix

### PR DESCRIPTION
**Pull request by magnus-ISU**
Also makes -t option show an error, as it should, because it is an invalid option, and updates the `usage` function accordingly.

For an example of how this is useful, if before you wanted to do

```
pmenu <<! | sh
IMG:/home/user/Pictures/icons/firefox.png  firefox
IMG:/home/user/Pictures/icons/xterm.png   xterm
IMG:/home/user/Pictures/icons/urxvt.png   urxvt
IMG:/home/user/Pictures/icons/st.png      st
IMG:/home/user/Pictures/icons/poweroff.png poweroff
IMG:/home/user/Pictures/icons/reboot.png  reboot
!
```

now you can just do

```
pmenu -P /home/user/Pictures/icons/ <<! | sh
IMG:firefox.png  firefox
IMG:xterm.png   xterm
IMG:urxvt.png   urxvt
IMG:st.png      st
IMG:poweroff.png poweroff
IMG:reboot.png  reboot
!
```

### CODE REVIEW

**Comment by magnus-ISU** [comment]
Oops, this commit also adds a `.gitignore`.

I feel like pmenu should have one in the first place, that's why I added it, but if you want I can recreate the pull request with it removed.

**Comment by phillbush** [comment]
Oh, that `-t` was there when I tested something and then removed... Sorry about that, I should have done it in a test branch...

On line 45, that `= 0` should be initialized to `= NULL` because `path_prefix` is a pointer.  
(Or the initialization can be removed, as static values are initialized to zero anyway.)

On the `.gitignore`,  I'm just not used to it and do not use it on my projects. But I can add it if contributors feel more comfortable with a `.gitignore`.

**Comment by phillbush** [comment]
Nice, I'm gonna merge it!

Just one more thing: the code has a `emalloc` function that calls malloc and checks for error.  
For consistency with the rest of the code, the call to `malloc(3)` and the test for whether it is NULL should be replaced by a call to `emalloc`.

**Comment by magnus-ISU** [comment]
Okay, I fixed the =0 and used emalloc

**Comment by phillbush** [comment]
the estrdup_prefix function used emalloc but was defined before emalloc's definition.  
That caused a warning.  
I replaced the function in my last commit.

**Pull request merged**
